name: Deploy

on:
    push:
        tags: [ 'v*.*.*' ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Download Dalamud
                run: |
                    mkdir dalamud
                    cd dalamud
                    wget https://github.com/goatcorp/dalamud-distrib/raw/main/latest.zip
                    unzip latest.zip

            -   name: Setup .NET
                uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: 7.x

            -   name: Restore dependencies
                run: dotnet restore

            -   name: Build
                id: build
                env:
                    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                run: dotnet build --no-restore -c Release -p:IsCI=true

            -   name: Prepare for deploy
                if: steps.build.outcome == 'success'
                run: |
                    cp \
                        bin/x64/Release/net7.0-windows/heliosphere-plugin/latest.zip \
                        latest.zip

                    python3 make_repo.py \
                        latest.zip \
                        changelog.txt \
                        https://repo.heliosphere.app/latest.zip \
                        repo.json

                    tar -I 'zstd -14' -cvf payload.tar.zst \
                        repo.json \
                        latest.zip

            -   name: Deploy
                if: steps.build.outcome == 'success'
                env:
                    DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
                    DEPLOY_IP: ${{ secrets.DEPLOY_IP }}
                    DEPLOY_SERVER_FINGERPRINT: ${{ secrets.DEPLOY_SERVER_FINGERPRINT }}
                    TUNNEL_SERVICE_TOKEN_ID: ${{ secrets.TUNNEL_SERVICE_TOKEN_ID }}
                    TUNNEL_SERVICE_TOKEN_SECRET: ${{ secrets.TUNNEL_SERVICE_TOKEN_SECRET }}
                run: |
                    sudo mkdir -p --mode=0755 /usr/share/keyrings
                    curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
                    echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared' "$(cat /etc/lsb-release | grep DISTRIB_CODENAME | cut -d'=' -f2)" 'main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
                    sudo apt-get update && sudo apt-get install -y cloudflared
                    mkdir -p "$HOME/.ssh"
                    echo "$DEPLOY_KEY" > "$HOME/.ssh/id_ed25519"
                    echo "$DEPLOY_IP $DEPLOY_SERVER_FINGERPRINT" > "$HOME/.ssh/known_hosts"
                    echo -e "Host $DEPLOY_IP\n\tProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h" > $HOME/.ssh/config
                    chmod 0700 "$HOME/.ssh"
                    chmod 0600 "$HOME/.ssh/known_hosts" "$HOME/.ssh/config" "$HOME/.ssh/id_ed25519"
                    ssh heliosphere@"$DEPLOY_IP" deploy plugin < payload.tar.zst
